// This file provides the HTML (route links generated by the Navbar component)for the mobile/small screen navigation menu
import React, { useState } from 'react';
import { IoCloseOutline } from "react-icons/io5";
// Use plain anchors and history API to avoid importing `react-router-dom` at module load.
import { NavLink } from "../interfaces/NavLink";

function MobileMenu({ navLinks, close }: { navLinks: NavLink[]; close: () => void }) {
  const [animation, setAnimation] = useState(false);

    React.useEffect(() => {
        setAnimation(true);
        const onResize = () => {
            if (window.innerWidth >= 640) {
                close();
            }
        };

        window.addEventListener("resize", onResize);

        return () => {
            window.removeEventListener("resize", onResize);
        };
    }, [close]);

  return (
    <div>
        <div className="top-0 1-0 h-screen w-full backdrop-blur-sm bg-forrest bg-opacity-60 fixed inset-0"></div>
        <div className="fixed inset-0 top 1-0 p-5">
            <div className={`w-full bg-ivory rounded-xl p-5 transition-all ${animation ? "scale-100" : "scale-95"}`}>
                <div className="flex items-center justify-between">
                    <h1 className="text-forrest font-serif">Menu</h1>
                    <IoCloseOutline className="text-forrest w-7 h-7 hover:scale-110 transition-all cursor-pointer" onClick={() => {close()}}/>
                </div> 
                <div className="mt-5">
                { navLinks.map(({ text, path }, index: number) => {
                    const handleNav = (e: React.MouseEvent) => {
                        e.preventDefault();
                        if (path) {
                            window.history.pushState({}, '', path);
                            window.dispatchEvent(new PopStateEvent('popstate'));
                            close();
                        }
                    };
                    return (
                        <div key={path ?? `mobileNav${index}`} className="transform transition-transform hover:scale-110 origin-left">
                            <a
                                className="block py-2 text-forrest font-serif hover:underline active:underline focus:underline underline-offset-4 transition-all"
                                href={path}
                                onClick={handleNav}
                            >
                                { text }
                            </a>
                        </div>
                    );
                })}
            </div> 
            </div>
        </div>
    </div>
  )
}

export default MobileMenu