// This file provides the HTML (route links generated by the Navbar component)for the mobile/small screen navigation menu
import { motion } from "framer-motion";
import React, { useState } from 'react';
import { IoCloseOutline } from "react-icons/io5";
import { Link } from "react-router-dom";
import { NavLink } from "../interfaces/NavLink";

function MobileMenu({ navLinks, close }: { navLinks: NavLink[]; close: () => void }) {
  const [animation, setAnimation] = useState(false);

    React.useEffect(() => {
        setAnimation(true);
        const onResize = () => {
            if (window.innerWidth >= 640) {
                close();
            }
        };

        window.addEventListener("resize", onResize);

        return () => {
            window.removeEventListener("resize", onResize);
        };
    }, [close]);

  return (
    <div>
        <div className="top-0 1-0 h-screen w-full backdrop-blur-sm bg-forrest bg-opacity-60 fixed inset-0"></div>
        <div className="fixed inset-0 top 1-0 p-5">
            <div className={`w-full bg-ivory rounded-xl p-5 transition-all ${animation ? "scale-100" : "scale-95"}`}>
                <div className="flex items-center justify-between">
                    <h1 className="text-forrest font-serif">Menu</h1>
                    <IoCloseOutline className="text-forrest w-7 h-7 hover:scale-110 transition-all cursor-pointer" onClick={() => {close()}}/>
                </div> 
                <div className="mt-5">
                { navLinks.map(({ text, path }, index: number) => {
                    return (
                        <motion.div key={path ?? `mobileNav${index}`} whileHover={{ scale: 1.1, originX: 0 }} transition={{ type: "spring", stiffness: "300" }}>
                            <Link className="block py-2 text-forrest font-serif" to={ path }>{ text }</Link>
                        </motion.div>
                    );
                })}
            </div> 
            </div>
        </div>
    </div>
  )
}

export default MobileMenu