// This file provides the HTML (route links generated by the Navbar component)for the navigation menu
// Avoid importing `react-router-dom` at module load — use anchors and history API instead.
import { NavLink } from "../interfaces/NavLink";

function WebMenu({ navLinks }: { navLinks: NavLink[] }) {

  return (
    <div className="hidden sm:block">
        <div className="bg-white text-forrest font-serif border border-forrest rounded-full px-5 py-3 gap-6 items-center flex shadow-md">
        { navLinks.map(({ text, path }, index: number) => {
            const handleNav = (e: React.MouseEvent) => {
                e.preventDefault();
                if (path) {
                    window.history.pushState({}, '', path);
                    window.dispatchEvent(new PopStateEvent('popstate'));
                }
            };
            return (
              <div key={path ?? `webNav${index}`}> 
                <a className="hover:text-forrest/60 cursor-pointer" href={path} onClick={handleNav}>{text}</a>
              </div>
            );
          })}
        </div>
    </div>
  )
}

export default WebMenu