// This file provides the HTML (route links generated by the Navbar component)for the navigation menu
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { NavLink } from "../interfaces/NavLink";

function WebMenu({ navLinks }: { navLinks: NavLink[] }) {

  return (
    <div className="hidden sm:block">
        <div className="bg-white text-forrest font-serif border border-forrest rounded-full px-5 py-3 gap-6 items-center flex shadow-md">
        { navLinks.map(({ text, path }, index: number) => {
            return (
              <motion.div key={path ?? `webNav${index}`} whileHover={{ scale: 1.3, originX: 0 }}>
                <Link className="hover:text-forrest/60 cursor-pointer" to={path}>{text}</Link>
              </motion.div>
            );
          })}
        </div>
    </div>
  )
}

export default WebMenu